name: Deploy to Server
description: Uses a FE build to make a deploy to a specific server


inputs:
  imageTag:
    description: "Which Docker image tag you'd like to deploy ? (List of all available tags: https://docker-repo.amana.vpn/v2/movedigital/mwm-admin-frontend/tags/list)"
    default: latest
    required: true

  namespace:
    description: "Which server we want to deploy to? Valid options are: 'test', 'stage', 'prod'"
    required: true
    default: test


runs:
  using: composite
  env:
    imagePath: docker-repo.amana.vpn/movedigital/mwm-admin-frontend:${{ inputs.imageTag }}

  steps:
    - name: Validate input
      if: inputs.namespace != 'test' && inputs.namespace != 'stage' && inputs.namespace != 'prod'
      shell: bash
      run: |
        echo "Invalid 'namespace' = '${{ inputs.namespace }}'"
        echo "Valid 'namespace' options are:"
        echo "  'test'"
        echo "  'stage'"
        echo "  'prod'"
        exit 1

    - name: Deploy
      shell: bash
      run: |
        echo "Deploy to namespace: ${{ inputs.namespace }}"
        echo "Image: ${{ env.imagePath }}"
