name: Deploy to Server
description: Uses a FE build to make a deploy to a specific server


inputs:
  imageTag:
    description: "Which Docker image tag you'd like to deploy ? (List of all available tags: https://docker-repo.amana.vpn/v2/movedigital/mwm-admin-frontend/tags/list)"
    default: latest
    required: true

  namespace:
    description: "Which server we want to mane a deploy? Valid values are: 'test', 'stage', 'prod'"
    required: true
    default: test

  MSTEAMS_WEBHOOK:
    description: "If we want to send a deploy message in MS Teams then we need to provide the Webhook ENV VAR secret"
    required: false


runs:
  using: composite
  steps:
    - name: Validate input
      shell: bash
      run: |
        if [[ '${{ inputs.namespace }}' == 'test' || '${{ inputs.namespace }}' == 'stage' || '${{ inputs.namespace }}' == 'prod' ]]; then
          echo "Input property 'namespace' has a valid value of '${{ inputs.namespace }}'"
        else 
          echo "Input property 'namespace' has invalid value of '${{ inputs.namespace }}'"
          echo "Valid 'namespace' values are:"
          echo "  'test'"
          echo "  'stage'"
          echo "  'prod'"
          exit 1
        fi

    - name: Deploy
      env:
        imagePath: docker-repo.amana.vpn/movedigital/mwm-admin-frontend:${{ inputs.imageTag }}
        serverUrl: http://mwm-admin-fe-${{ inputs.namespace }}.int.kube.digital
      shell: bash
      run: |
        echo "Deploy to namespace: ${{ inputs.namespace }}"
        echo "Image: ${{ env.imagePath }}"
        echo "Server URL: ${{ env.serverUrl }}"
        echo "Commit message: $(git log --format=%B -n 1 ${{ github.sha }} | head -n 1)"
        
    - name: Get commit message from SHA
      id: commitMessage
      shell: bash
      run: "echo '::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }} | head -n 1)'"

    - name: Send success message
      if: inputs.MSTEAMS_WEBHOOK
      uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
      env:
        serverUrl: http://mwm-admin-fe-${{ inputs.namespace }}.int.kube.digital
      with:
        webhook_url: ${{ inputs.MSTEAMS_WEBHOOK }}
        theme-color: Success
        summary: Deploy ${{ github.event.inputs.imageTag }} success
        title: Deploy ${{ github.event.inputs.imageTag }} success
        sections: |
          - activityImage: "{gh:avatar-url}"
            activityTitle: "Successful deploy of version ${{ github.event.inputs.imageTag }}"
            activitySubtitle: "You can access the server here: [${{ env.serverUrl }}](${{ env.serverUrl }})<br/>Deployed commit: [${{ steps.commitMessage.outputs.message }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
