name: Deploy to Server
description: Uses a FE build to make a deploy to a specific server


inputs:
  namespace:
    description: "Which server we want to deploy to? Valid options are: 'test', 'stage', 'prod'"
    required: true
    default: test


runs:
  using: composite
  steps:
    - name: Validate input
      if: inputs.namespace != 'test' && inputs.namespace != 'stage' && inputs.namespace != 'prod'
      shell: bash
      run: |
        echo "Invalid 'namespace' = '${{ inputs.namespace }}'"
        echo "Valid namespace options are:"
        echo "  test"
        echo "  stage"
        echo "  prod"
        exit 1

    - name: Deploy
      shell: bash
      run: echo "Deploy to namespace ${{ inputs.namespace }}"
