name: Get Repo
description: Makes sure we checkout and install our repo correctly


inputs:
  checkoutBranch:
    description: Which branch we want to pull from the repo ?
    default: ${{ github.head_ref }}
    required: false

  shell:
    description: Which shell client to use ?
    required: false
    default: bash


runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ inputs.checkoutBranch }}
