name: Get Repo
description: Makes sure we checkout and install our repo correctly


inputs:
  checkoutBranch:
    description: Which branch we want to pull from the repo ?
    default: ${{ github.head_ref }}
    required: false

  shell:
    description: Which shell client to use ?
    required: false
    default: bash


runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ inputs.checkoutBranch }}

    - name: Setup Node
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14'

    - name: Cache node_modules
      id: cacheNodeModules
      uses: actions/cache@v2.1.7
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('package.json') }}

    - name: Install Node Dependencies
      if: steps.cacheNodeModules.outputs.cache-hit != 'true'
      shell: ${{ inputs.shell }}
      run: npm ci
