# When a PR has a tag label of "autorelease: pending"
# then this Github Action will automatically merge the PR
# (when all PR merge requirelemts are met: such as unit tests, PR title check)
name: Automerge

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "autorelease: pending"
