name: Check PR title

on:
  pull_request:
    branches:
      - master
      - main
      - v*

jobs:
  conventional_commit_check:
    runs-on: ubuntu-18.04
    steps:
      - uses: amannn/action-semantic-pull-request@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
