name: Check PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  conventional_commit_check:
    runs-on: [ self-hosted, ubuntu-18.04, test ]
    steps:
      - uses: amannn/action-semantic-pull-request@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
