name: Deploy after Release

on:
  push:
    tags:
      - 'v*'


jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Debug
        run: |
          echo github.event_name = ${{ github.event_name }}
          echo github.event.action = ${{ github.event.action }}
          echo $(git for-each-ref --sort=-taggerdate --format '%(refname:lstrip=2)' --count=1 refs/tags)

      - name: Generate release version
        id: releaseVersion
        run: |
          echo github.event_name = ${{ github.event_name }}
          echo github.event.action = ${{ github.event.action }}
          echo $(git for-each-ref --sort=-taggerdate --format '%(refname:lstrip=2)' --count=1 refs/tags)
          
          export VERSION=$(git for-each-ref --sort=-taggerdate --format '%(refname:lstrip=2)' --count=1 refs/tags | sed 's/v//)
          echo "::set-output name=version::${VERSION}"

      - name: Debug
        run: |
          echo ${{ steps.releaseVersion.outputs.version }}
