name: Deploy after Release

on:
  push:
    tags:
      - '*'


jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Debug
        run: |
          echo github.event_name = ${{ github.event_name }}
          echo github.event.action = ${{ github.event.action }}
