name: Deploy after Release

on:
  push:
    tags:
      - 'v*'


jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Debug
        run: |
          echo github.event_name = ${{ github.event_name }}
          echo github.event.action = ${{ github.event.action }}
          git for-each-ref --sort=-taggerdate --format '%(refname:lstrip=2)' --count=1 refs/tags
