name: E2E tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
      - main

  push:
    branches:
      - master
      - main

concurrency:
  group: regressions-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
      - name: Build
        run: |
          echo Building
          sleep 10
          echo Build successfully completed


  e2e-start-message:
    needs: setup
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Announce E2E tests start
        id: e2e-start-message
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: 'Info'
          summary: "Starting E2E tests"
          title: "Starting E2E tests"
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "E2E tests triggered by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "You can check progress here: {gh:run-number-link}"

  e2e:
    needs: setup
    runs-on: ubuntu-18.04
    container: ivandimanov/rfq-github-e2e:latest
    timeout-minutes: 30
    env:
      RESULTS_PATH: ${{ github.workspace }}
    strategy:
      matrix:
        fixtures:
          - admin_iwm.testcafe.js
          - admin_iwm2.testcafe.js
#           - admin_iwm7.testcafe.js
#           - admin_iwm9.testcafe.js

    steps:
      - name: initiate
        uses: actions/checkout@v2.3.4

      - name: Run E2E Tests
        id: e2e
        run: node --unhandled-rejections=strict ./scripts/test.js ${{ matrix.fixtures }}
