name: Get release version

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Get release version
        id: releaseVersion
        run: |
          export HEAD_REF=${{ github.head_ref }}
          echo ::set-output name=tagName::${HEAD_REF#release-}

      - run: "echo '${{ steps.releaseVersion.outputs.tagName }}'"
