name: Get release version

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-18.04
    outputs:
      versionNumber: ${{ steps.releaseVersion.outputs.versionNumber }}

    steps:
      - name: Get release version
        id: releaseVersion
        run: |
          export VERSION_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP "release \K\d+\.\d+\.\d+")
          echo ::set-output name=versionNumber::${VERSION_NUMBER}

  deploy-to-stage:
    needs: version
    if: needs.version.outputs.versionNumber
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy to Stage server
        run: |
          echo '${{ needs.version.outputs.versionNumber }}'
