name: Get release version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Get release version
        id: releaseVersion
        run: |
          export COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export TAG_NAME=echo ${COMMIT_MESSAGE} | grep -oP "release \K\d+\.\d+\.\d+"
          echo ::set-output name=tagName::${TAG_NAME}

      - run: "echo '${{ steps.releaseVersion.outputs.tagName }}'"
