name: Get release version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Get release version
        id: releaseVersion
        run: |
          export TAG_NAME=$(echo "${{ github.event.head_commit.message }}" | grep -oP "release \K\d+\.\d+\.\d+")
          echo ::set-output name=tagName::${TAG_NAME}

      - run: "echo '${{ steps.releaseVersion.outputs.tagName }}'"
