name: Get release version

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Get release version
        id: releaseVersion
        run: echo ::set-output name=tagName::${${{ github.head_ref }}#release-}

      - run: "echo '${{ steps.releaseVersion.outputs.tagName }}'"
