name: Test MariaDB

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup maria db
        uses: ankane/setup-mariadb@v1
        with:
          mariadb-version: 10.6
          database: test_db
