name: NGINX

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Create Demo page
        run: |
          mkdir ./build
          echo "<h1>Demo Page</h1>" >> ./build/index.html

      - name: Start local server
        run: |
          docker build --tag frontend:latest .
          docker run --detach --net=host frontend:latest
          sleep 20
          docker image ls

      - name: Debug
        run: docker image ls

      - name: Create login session
        run: |
          sleep 20
          time curl http://localhost:8080
          time curl http://localhost:8080/index.html
          time curl http://localhost:8080/api/ping
