name: Notification

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Send Notification'

jobs:
  send-message:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Send message
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: 'Success'
          summary: "Test message"
          title: "Test message"
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "All E2E tests triggered by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) have successfully passed"
              activitySubtitle: "You can view a detailed summary here: [${{ github.event.workflow_run.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/) ++ message:${{ github.event.inputs.message }}"
