name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      semverType:
        description: What kind of release version we want to trigger ?
        required: true
        type: choice
        options:
          - major
          - minor
        default: minor

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        if: ${{ github.event.inputs.semverType }}
        uses: actions/checkout@master

      - name: Make an empty commit with valid message to trigger "Please Release Bot" minor version release
        if: ${{ github.event.inputs.semverType }}
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "${{ github.event.inputs.semverType == 'major' && 'feat!:' || 'feat:' }} Manually triggered release"
          empty: true

      - name: Release Please Bot
        id: release
        uses: GoogleCloudPlatform/release-please-action@v2.35.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-types: '[{"type":"style","section":"Styling","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Send pending message
        if: ${{ steps.release.outputs.pr && !steps.release.outputs.sha }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Info
          summary: Pending release PR created
          title: Pending release PR created
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "PR is pending merge for MoveUI release using [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "Pending PR can be found here: [#${{ steps.release.outputs.pr }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.release.outputs.pr }})"

      - name: Send success message
        if: ${{ steps.release.outputs.pr && steps.release.outputs.sha }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Success
          summary: Release ${{ steps.release.outputs.tag_name }} success
          title: Release ${{ steps.release.outputs.tag_name }} success
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "MoveUI was successfully released under [${{ steps.release.outputs.tag_name }}](${{ steps.release.outputs.html_url }}) by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "Merged release PR can be found here: [#${{ steps.release.outputs.pr }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.release.outputs.pr }})"

      - name: Deploy to Stage
        if: ${{ steps.release.outputs.pr && steps.release.outputs.sha }}
        run: echo "Deploy ${{ steps.release.outputs.tag_name }} to Stage server"

      - name: Send error message
        if: ${{ !steps.release.outputs.pr }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Error
          summary: Release error
          title: Release error
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "There is an error with MoveUI release caused by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "One thing that may cause problem is the commit message: `${{ github.event.head_commit.message }}`"
