name: Release name check

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Release Please Bot
        id: release
        uses: GoogleCloudPlatform/release-please-action@v3.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-types: '[{"type":"style","section":"Styling","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - run: echo '${{ toJson(steps.release.outputs) }}'

