name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      defaultBranch:
        description: Branch to open pull release PR against

jobs:
  versioning:
    runs-on: ubuntu-18.04

    steps:
      - name: Release Please Bot
        id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-types: '[{"type":"style","section":"Styling","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          default-branch: github.event.inputs.message

      - name: Send success message
        if: ${{ steps.release.outputs.release_created }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Success
          summary: Release success
          title: Release success
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "MoveUI was successfully released by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "You can view a detailed summary here: [${{ github.event.workflow_run.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/) sha=${{ steps.release.outputs.sha }} pr=${{ steps.release.outputs.pr }}"

      - name: Send error message
        if: ${{ !steps.release.outputs.release_created }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Error
          summary: Release error
          title: Release error
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "There is an error with MoveUI release caused by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "You can view a detailed summary here: [${{ github.event.workflow_run.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/) sha=${{ steps.release.outputs.sha }} pr=${{ steps.release.outputs.pr }}"
