name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      defaultBranch:
        description: Branch to open pull release PR against

jobs:
  versioning:
    runs-on: ubuntu-18.04

    steps:
      - name: Release Please Bot
        id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-types: '[{"type":"style","section":"Styling","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          default-branch: ${{ github.event.inputs.defaultBranch }}

      - name: Pending release PR created
        if: ${{ steps.release.outputs.pr && !steps.release.outputs.sha }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Info
          summary: Pending PR for release ${{ steps.release.outputs.tag_name }}
          title: Pending PR for release ${{ steps.release.outputs.tag_name }}
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "PR is pending merge for MoveUI release ${{ steps.release.outputs.major }}-${{ steps.release.outputs.minor }}-${{ steps.release.outputs.patch }} [${{ steps.release.outputs.tag_name }}](${{ steps.release.outputs.html_url }}) using [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "Pending PR can be found here: [#${{ steps.release.outputs.pr }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.release.outputs.pr }})"

      - name: Release success
        if: ${{ steps.release.outputs.pr && steps.release.outputs.sha }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Success
          summary: Release ${{ steps.release.outputs.tag_name }} success
          title: Release ${{ steps.release.outputs.tag_name }} success
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "MoveUI was successfully released under [${{ steps.release.outputs.tag_name }}](${{ steps.release.outputs.html_url }}) by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "Merged release PR can be found here: [#${{ steps.release.outputs.pr }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.release.outputs.pr }})"

      - name: Send error message
        if: ${{ !steps.release.outputs.pr }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with: 
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          theme-color: Error
          summary: Release error
          title: Release error
          sections: |
            - activityImage: "{gh:avatar-url}"
              activityTitle: "There is an error with MoveUI release caused by [this commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              activitySubtitle: "You can view a detailed summary here: [${{ github.event.workflow_run.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/)"
