name: Trigger release

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Make an empty commit with valid message to trigger "Please Release Bot" minor version release
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "feat: Manually triggered release"
          empty: true

      - name: Release Please Bot
        uses: GoogleCloudPlatform/release-please-action@v2.35.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-types: '[{"type":"style","section":"Styling","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
