name: Trigger release

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-18.04

    steps:
      - name: Make an empty commit with valid message to trigger "Please Release Bot" minor version release
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "feat: Manually triggered release"
          empty: true
